// Generator for docs/fixtures/products.json. NOT a test — emits the JSON
// to stdout so the fixture is single-sourced from the implementation.
//
// Run with `pnpm --filter @oddzilla/types exec tsx src/_gen-products-fixture.ts`
// from repo root and pipe to docs/fixtures/products.json.

import { priceTiple, priceTippot, parseProbability } from "./products.js";

const tipleCases: Array<{ name: string; probabilities: string[]; marginBp: number }> = [
  { name: "two even-money legs, 15% margin", probabilities: ["0.5", "0.5"], marginBp: 1500 },
  { name: "three even-money legs, 15% margin (offered < 1 — high-prob, bad bet, but math is honest)", probabilities: ["0.5", "0.5", "0.5"], marginBp: 1500 },
  { name: "three longer-shot legs, 15% margin", probabilities: ["0.25", "0.30", "0.20"], marginBp: 1500 },
  { name: "five 20% legs, 0% margin (fair pricing)", probabilities: ["0.20", "0.20", "0.20", "0.20", "0.20"], marginBp: 0 },
  { name: "two longshots, 25% margin", probabilities: ["0.10", "0.10"], marginBp: 2500 },
];

const tippotCases: Array<{ name: string; probabilities: string[]; marginBp: number }> = [
  { name: "three even-money legs, 15% margin", probabilities: ["0.5", "0.5", "0.5"], marginBp: 1500 },
  { name: "five 20% legs, 0% margin", probabilities: ["0.20", "0.20", "0.20", "0.20", "0.20"], marginBp: 0 },
  { name: "four mixed-prob legs, 15% margin", probabilities: ["0.30", "0.40", "0.50", "0.60"], marginBp: 1500 },
];

const out = {
  _comment:
    "Golden fixture for Tiple + Tippot pricing. Generated by packages/types/src/_gen-products-fixture.ts. Both the TS implementation in packages/types/src/products.ts and the Go implementation in services/<svc>/internal/products/ MUST produce these exact strings for these exact inputs. Any divergence means the bookmaker and the frontend will disagree on payout — a money-losing bug. Regenerate with `pnpm --filter @oddzilla/types exec tsx src/_gen-products-fixture.ts > docs/fixtures/products.json`.",
  tiple: tipleCases.map((tc) => {
    const probs = tc.probabilities.map(parseProbability);
    const q = priceTiple(probs, tc.marginBp);
    return {
      name: tc.name,
      probabilities: tc.probabilities,
      marginBp: tc.marginBp,
      offeredOdds: q.offeredOdds,
      fairProbability: q.fairProbability,
    };
  }),
  tippot: tippotCases.map((tc) => {
    const probs = tc.probabilities.map(parseProbability);
    const q = priceTippot(probs, tc.marginBp);
    return {
      name: tc.name,
      probabilities: tc.probabilities,
      marginBp: tc.marginBp,
      tiers: q.tiers,
    };
  }),
};

process.stdout.write(JSON.stringify(out, null, 2) + "\n");
